[build-system]
requires = ["setuptools>=70.0.0", "pip>=23.3"]
build-backend = "setuptools.build_meta"

[project]
name = "autoprot"
version = "0.3.0"
description = "Automated Proteomics Analysis"
authors = [
    { name = "Julian Bender", email = "julian.bender@uni-wuerzburg.de" },
    { name = "Johannes Zimmermann", email = "johannes.zimmermann@uni-wuerzburg.de" },
    { name = "Friedel Drepper", email = "drepper@uni-freiburg.de" },
    { name = "Wignand Mühlhäuser" }
]
license = { text = "BSD-3-Clause" }
urls = { Homepage = "https://www.warscheidlab.de" }
dependencies = [
    "adjustText>=0.7.3",
    "biopython>=1.78",
    "gprofiler-official>=1.0.0",
    "logomaker>=0.8",
    "matplotlib>=3.8.4",
    "matplotlib-venn>=0.11.7",
    "missingno>=0.4.2",
    "numpy>=1.22.3",
    "pandas>=2.0.0",
    "plotly>=5.8.0",
    "requests>=2.31.0",
    "scikit-learn>=1.0.1",
    "scipy>=1.7.3",
    "seaborn>=0.13.2",
    "statsmodels>=0.13.2",
    "UpSetPlot>=0.8.0"
]

[project.optional-dependencies]
docs = [
    "Sphinx>=7.3.7",
    "numpydoc>=1.7.0",
    "pydata-sphinx-theme>=0.15.2",
    "myst-parser>=3.0.1"
]

testing = [
    "ruff",
    "pytest"
]

[tool.setuptools.packages.find]
include = ["autoprot"]

[tool.pixi.workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
autoprot = { path = ".", editable = true }

[tool.pixi.dependencies]
pixi-pycharm = ">=0.0.9,<0.0.10"
r-base = ">=4.4.3,<4.5"
r-tidyverse = ">=2.0.0,<3"
r-tmvtnorm = ">=1.7,<2"
bioconductor-limma = ">=3.28.10,<4"
bioconductor-vsn = ">=3.74"
bioconductor-rankprod = ">=3.32.0,<4"
bioconductor-pcamethods = ">=1.98.0,<2"
bioconductor-impute = ">=1.80.0,<2"
bioconductor-summarizedexperiment = ">=1.36.0,<2"
r-pak = ">=0.9.0,<0.10"
openpyxl = ">=3.1.5,<4"
xlsxwriter = ">=3.2.9,<4"
notebook = ">=7.4.7,<8"
pip = ">=25.2,<26"
pyarrow = ">=22.0.0,<23"
zlib = ">=1.3.1,<2"

[tool.pixi.environments]
default = { solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
testing = { features = ["testing"], solve-group = "default" }

[tool.pixi.tasks]
