from setuptools import setup

setup(
    name="autoprot",
    version="0.3.0",
    packages=["autoprot"],
    url="www.warscheidlab.de",
    license="BSD-3-Clause",
    author="The autoprot contributors",
    author_email="julian.bender@uni-wuerzburg.de",
    description="Automated Proteomics Analysis",
    install_requires=[
        "adjustText>=0.7.3",
        "biopython>=1.78",
        "gprofiler-official>=1.0.0",
        "logomaker>=0.8",
        "matplotlib>=3.8.4",
        "matplotlib-venn>=0.11.7",
        "missingno>=0.4.2",
        "numpy>=1.22.3",
        "pandas>=2.0.0",
        "plotly>=5.8.0",
        "requests>=2.31.0",
        "scikit-learn>=1.0.1",
        "scipy>=1.7.3",
        "seaborn>=0.13.2",
        "statsmodels>=0.13.2",
        "UpSetPlot>=0.8.0",
        "setuptools~=65.6.3",
        "pip>=23.3",
    ],
)
